export const 
    ANSWER_CHOISE = 'ANSWER_CHOISE',
    SUCCESS_ANSWER = 'SUCCESS_ANSWER',
    ERROR_ANSWER = 'ERROR_ANSWER',
    NEXT_QUESTION = 'NEXT_QUESTION',
    AGAIN_QUIZ = 'AGAIN_QUIZ',
    COUNT_PERCENT_SUCCESS = 'COUNT_PERCENT_SUCCESS',
    COUNT_PERCENT_NOT_SUCCESS = 'COUNT_PERCENT_NOT_SUCCESS',
    BEGIN_QUIZ = 'BEGIN_QUIZ',
    COME_BACK_HOME = 'COME_BACK_HOME',
    REQUEST_QUIZ = 'REQUEST_QUIZ'
